/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1

// BundleMetadataApplyConfiguration represents a declarative configuration of the BundleMetadata type for use
// with apply.
//
// BundleMetadata is a representation of the identifying attributes of a bundle.
type BundleMetadataApplyConfiguration struct {
	// name is required and follows the DNS subdomain standard as defined in [RFC 1123].
	// It must contain only lowercase alphanumeric characters, hyphens (-) or periods (.),
	// start and end with an alphanumeric character, and be no longer than 253 characters.
	Name *string `json:"name,omitempty"`
	// version is required and references the version that this bundle represents.
	// It follows the semantic versioning standard as defined in https://semver.org/.
	Version *string `json:"version,omitempty"`
}

// BundleMetadataApplyConfiguration constructs a declarative configuration of the BundleMetadata type for use with
// apply.
func BundleMetadata() *BundleMetadataApplyConfiguration {
	return &BundleMetadataApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *BundleMetadataApplyConfiguration) WithName(value string) *BundleMetadataApplyConfiguration {
	b.Name = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *BundleMetadataApplyConfiguration) WithVersion(value string) *BundleMetadataApplyConfiguration {
	b.Version = &value
	return b
}
