/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.21. DO NOT EDIT.

package v1

import (
	apismetav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ClusterObjectSetStatusApplyConfiguration represents a declarative configuration of the ClusterObjectSetStatus type for use
// with apply.
//
// ClusterObjectSetStatus defines the observed state of a ClusterObjectSet.
//
// The completedAt removal guard lives here at the parent level because a
// field-level transition rule is skipped when the field is absent from an
// update, which would otherwise allow the timestamp to be cleared and re-set.
type ClusterObjectSetStatusApplyConfiguration struct {
	// conditions is an optional list of status conditions describing the state of the
	// ClusterObjectSet.
	//
	// The Ready condition represents whether the revision has fully rolled out:
	// - True / Ready: all phases are complete and all objects pass their probes.
	// - False / Incomplete: one or more phases are not yet complete.
	// - False / Blocked: reconciliation requires manual intervention (e.g. a mutable
	// referenced Secret, resolved-content drift, or an object ownership collision).
	// - False / Invalid: a preflight validation error was encountered.
	// - False / Archived: the revision is archived; teardown is in progress or complete.
	// - False / ProgressDeadlineExceeded: the revision did not complete within
	// spec.progressDeadlineMinutes.
	// - Unknown / ReconcileError: reconciliation returned an error.
	// - Unknown / TeardownError: teardown returned an error.
	// - Unknown / InternalError: an internal controller error occurred.
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// observedPhases records the content hashes of resolved phases
	// at first successful reconciliation. This is used to detect if
	// referenced object sources were deleted and recreated with
	// different content. Each entry covers all fully-resolved object
	// manifests within a phase, making it source-agnostic.
	ObservedPhases []ObservedPhaseApplyConfiguration `json:"observedPhases,omitempty"`
	// completedAt is the timestamp at which the revision was first observed to be
	// ready, meaning it had successfully rolled out and all of its objects passed
	// their probes. It is set once and is immutable thereafter.
	CompletedAt *apismetav1.Time `json:"completedAt,omitempty"`
}

// ClusterObjectSetStatusApplyConfiguration constructs a declarative configuration of the ClusterObjectSetStatus type for use with
// apply.
func ClusterObjectSetStatus() *ClusterObjectSetStatusApplyConfiguration {
	return &ClusterObjectSetStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ClusterObjectSetStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *ClusterObjectSetStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithObservedPhases adds the given value to the ObservedPhases field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ObservedPhases field.
func (b *ClusterObjectSetStatusApplyConfiguration) WithObservedPhases(values ...*ObservedPhaseApplyConfiguration) *ClusterObjectSetStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithObservedPhases")
		}
		b.ObservedPhases = append(b.ObservedPhases, *values[i])
	}
	return b
}

// WithCompletedAt sets the CompletedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CompletedAt field is set to the value of the last call.
func (b *ClusterObjectSetStatusApplyConfiguration) WithCompletedAt(value apismetav1.Time) *ClusterObjectSetStatusApplyConfiguration {
	b.CompletedAt = &value
	return b
}
