/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/operator-framework/operator-controller/api/v1"
)

// ClusterExtensionRevisionSpecApplyConfiguration represents a declarative configuration of the ClusterExtensionRevisionSpec type for use
// with apply.
//
// ClusterExtensionRevisionSpec defines the desired state of ClusterExtensionRevision.
type ClusterExtensionRevisionSpecApplyConfiguration struct {
	// lifecycleState specifies the lifecycle state of the ClusterExtensionRevision.
	//
	// When set to "Active", the revision is actively managed and reconciled.
	// When set to "Archived", the revision is inactive and any resources not managed by a subsequent revision are deleted.
	// The revision is removed from the owner list of all objects previously under management.
	// All objects that did not transition to a succeeding revision are deleted.
	//
	// Once a revision is set to "Archived", it cannot be un-archived.
	//
	// It is possible for more than one revision to be "Active" simultaneously. This will occur when
	// moving from one revision to another. The old revision will not be set to "Archived" until the
	// new revision has been completely rolled out.
	LifecycleState *apiv1.ClusterExtensionRevisionLifecycleState `json:"lifecycleState,omitempty"`
	// revision is a required, immutable sequence number representing a specific revision
	// of the parent ClusterExtension.
	//
	// The revision field must be a positive integer.
	// Each ClusterExtensionRevision belonging to the same parent ClusterExtension must have a unique revision number.
	// The revision number must always be the previous revision number plus one, or 1 for the first revision.
	Revision *int64 `json:"revision,omitempty"`
	// phases is an optional, immutable list of phases that group objects to be applied together.
	//
	// Objects are organized into phases based on their Group-Kind. Common phases include:
	// - namespaces: Namespace objects
	// - policies: ResourceQuota, LimitRange, NetworkPolicy objects
	// - rbac: ServiceAccount, Role, RoleBinding, ClusterRole, ClusterRoleBinding objects
	// - crds: CustomResourceDefinition objects
	// - storage: PersistentVolume, PersistentVolumeClaim, StorageClass objects
	// - deploy: Deployment, StatefulSet, DaemonSet, Service, ConfigMap, Secret objects
	// - publish: Ingress, APIService, Route, Webhook objects
	//
	// All objects in a phase are applied in no particular order.
	// The revision progresses to the next phase only after all objects in the current phase pass their readiness probes.
	//
	// Once set, even if empty, the phases field is immutable.
	//
	// Each phase in the list must have a unique name. The maximum number of phases is 20.
	Phases []ClusterExtensionRevisionPhaseApplyConfiguration `json:"phases,omitempty"`
	// progressDeadlineMinutes is an optional field that defines the maximum period
	// of time in minutes after which an installation should be considered failed and
	// require manual intervention. This functionality is disabled when no value
	// is provided. The minimum period is 10 minutes, and the maximum is 720 minutes (12 hours).
	//
	// <opcon:experimental>
	ProgressDeadlineMinutes *int32 `json:"progressDeadlineMinutes,omitempty"`
	// collisionProtection specifies the default collision protection strategy for all objects
	// in this revision. Individual phases or objects can override this value.
	//
	// When set, this value is used as the default for any phase or object that does not
	// explicitly specify its own collisionProtection.
	//
	// The resolution order is: object > phase > spec
	CollisionProtection *apiv1.CollisionProtection `json:"collisionProtection,omitempty"`
}

// ClusterExtensionRevisionSpecApplyConfiguration constructs a declarative configuration of the ClusterExtensionRevisionSpec type for use with
// apply.
func ClusterExtensionRevisionSpec() *ClusterExtensionRevisionSpecApplyConfiguration {
	return &ClusterExtensionRevisionSpecApplyConfiguration{}
}

// WithLifecycleState sets the LifecycleState field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LifecycleState field is set to the value of the last call.
func (b *ClusterExtensionRevisionSpecApplyConfiguration) WithLifecycleState(value apiv1.ClusterExtensionRevisionLifecycleState) *ClusterExtensionRevisionSpecApplyConfiguration {
	b.LifecycleState = &value
	return b
}

// WithRevision sets the Revision field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Revision field is set to the value of the last call.
func (b *ClusterExtensionRevisionSpecApplyConfiguration) WithRevision(value int64) *ClusterExtensionRevisionSpecApplyConfiguration {
	b.Revision = &value
	return b
}

// WithPhases adds the given value to the Phases field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Phases field.
func (b *ClusterExtensionRevisionSpecApplyConfiguration) WithPhases(values ...*ClusterExtensionRevisionPhaseApplyConfiguration) *ClusterExtensionRevisionSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPhases")
		}
		b.Phases = append(b.Phases, *values[i])
	}
	return b
}

// WithProgressDeadlineMinutes sets the ProgressDeadlineMinutes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProgressDeadlineMinutes field is set to the value of the last call.
func (b *ClusterExtensionRevisionSpecApplyConfiguration) WithProgressDeadlineMinutes(value int32) *ClusterExtensionRevisionSpecApplyConfiguration {
	b.ProgressDeadlineMinutes = &value
	return b
}

// WithCollisionProtection sets the CollisionProtection field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CollisionProtection field is set to the value of the last call.
func (b *ClusterExtensionRevisionSpecApplyConfiguration) WithCollisionProtection(value apiv1.CollisionProtection) *ClusterExtensionRevisionSpecApplyConfiguration {
	b.CollisionProtection = &value
	return b
}
