/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.21. DO NOT EDIT.

package v1

import (
	apismetav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ClusterObjectSetStatusApplyConfiguration represents a declarative configuration of the ClusterObjectSetStatus type for use
// with apply.
//
// ClusterObjectSetStatus defines the observed state of a ClusterObjectSet.
//
// The completedAt removal guard lives here at the parent level because a
// field-level transition rule is skipped when the field is absent from an
// update, which would otherwise allow the timestamp to be cleared and re-set.
type ClusterObjectSetStatusApplyConfiguration struct {
	// conditions is an optional list of status conditions describing the state of the
	// ClusterObjectSet.
	//
	// The Progressing condition represents whether the revision is actively rolling out:
	// - When status is True and reason is RollingOut, the ClusterObjectSet rollout is actively making progress and is in transition.
	// - When status is True and reason is Retrying, the ClusterObjectSet has encountered an error that could be resolved on subsequent reconciliation attempts.
	// - When status is True and reason is Succeeded, the ClusterObjectSet has reached the desired state.
	// - When status is False and reason is Blocked, the ClusterObjectSet has encountered an error that requires manual intervention for recovery.
	// - When status is False and reason is Archived, the ClusterObjectSet is archived and not being actively reconciled.
	//
	// The Available condition represents whether the revision has been successfully rolled out and is available:
	// - When status is True and reason is ProbesSucceeded, the ClusterObjectSet has been successfully rolled out and all objects pass their readiness probes.
	// - When status is False and reason is ProbeFailure, one or more objects are failing their readiness probes during rollout.
	// - When status is Unknown and reason is Reconciling, the ClusterObjectSet has encountered an error that prevented it from observing the probes.
	// - When status is Unknown and reason is Archived, the ClusterObjectSet has been archived and its objects have been torn down.
	// - When status is Unknown and reason is Migrated, the ClusterObjectSet was migrated from an existing release and object status probe results have not yet been observed.
	//
	// The Succeeded condition represents whether the revision has successfully completed its rollout:
	// - When status is True and reason is Succeeded, the ClusterObjectSet has successfully completed its rollout. This condition is set once and persists even if the revision later becomes unavailable.
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// observedPhases records the content hashes of resolved phases
	// at first successful reconciliation. This is used to detect if
	// referenced object sources were deleted and recreated with
	// different content. Each entry covers all fully-resolved object
	// manifests within a phase, making it source-agnostic.
	ObservedPhases []ObservedPhaseApplyConfiguration `json:"observedPhases,omitempty"`
	// completedAt is the timestamp at which the revision was first observed to be
	// ready, meaning it had successfully rolled out and all of its objects passed
	// their probes. It is set once and is immutable thereafter.
	CompletedAt *apismetav1.Time `json:"completedAt,omitempty"`
}

// ClusterObjectSetStatusApplyConfiguration constructs a declarative configuration of the ClusterObjectSetStatus type for use with
// apply.
func ClusterObjectSetStatus() *ClusterObjectSetStatusApplyConfiguration {
	return &ClusterObjectSetStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ClusterObjectSetStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *ClusterObjectSetStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithObservedPhases adds the given value to the ObservedPhases field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ObservedPhases field.
func (b *ClusterObjectSetStatusApplyConfiguration) WithObservedPhases(values ...*ObservedPhaseApplyConfiguration) *ClusterObjectSetStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithObservedPhases")
		}
		b.ObservedPhases = append(b.ObservedPhases, *values[i])
	}
	return b
}

// WithCompletedAt sets the CompletedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CompletedAt field is set to the value of the last call.
func (b *ClusterObjectSetStatusApplyConfiguration) WithCompletedAt(value apismetav1.Time) *ClusterObjectSetStatusApplyConfiguration {
	b.CompletedAt = &value
	return b
}
