/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1

// ClusterExtensionSpecApplyConfiguration represents a declarative configuration of the ClusterExtensionSpec type for use
// with apply.
//
// ClusterExtensionSpec defines the desired state of ClusterExtension
type ClusterExtensionSpecApplyConfiguration struct {
	// namespace specifies a Kubernetes namespace.
	// This is the namespace where the provided ServiceAccount must exist.
	// It also designates the default namespace where namespace-scoped resources for the extension are applied to the cluster.
	// Some extensions may contain namespace-scoped resources to be applied in other namespaces.
	// This namespace must exist.
	//
	// The namespace field is required, immutable, and follows the DNS label standard as defined in [RFC 1123].
	// It must contain only lowercase alphanumeric characters or hyphens (-), start and end with an alphanumeric character,
	// and be no longer than 63 characters.
	//
	// [RFC 1123]: https://tools.ietf.org/html/rfc1123
	Namespace *string `json:"namespace,omitempty"`
	// serviceAccount specifies a ServiceAccount used to perform all interactions with the cluster
	// that are required to manage the extension.
	// The ServiceAccount must be configured with the necessary permissions to perform these interactions.
	// The ServiceAccount must exist in the namespace referenced in the spec.
	// The serviceAccount field is required.
	ServiceAccount *ServiceAccountReferenceApplyConfiguration `json:"serviceAccount,omitempty"`
	// source is required and selects the installation source of content for this ClusterExtension.
	// Set the sourceType field to perform the selection.
	//
	// Catalog is currently the only implemented sourceType.
	// Setting sourceType to "Catalog" requires the catalog field to also be defined.
	//
	// Below is a minimal example of a source definition (in yaml):
	//
	// source:
	// sourceType: Catalog
	// catalog:
	// packageName: example-package
	Source *SourceConfigApplyConfiguration `json:"source,omitempty"`
	// install is optional and configures installation options for the ClusterExtension,
	// such as the pre-flight check configuration.
	Install *ClusterExtensionInstallConfigApplyConfiguration `json:"install,omitempty"`
	// config is optional and specifies bundle-specific configuration.
	// Configuration is bundle-specific and a bundle may provide a configuration schema.
	// When not specified, the default configuration of the resolved bundle is used.
	//
	// config is validated against a configuration schema provided by the resolved bundle. If the bundle does not provide
	// a configuration schema the bundle is deemed to not be configurable. More information on how
	// to configure bundles can be found in the OLM documentation associated with your current OLM version.
	Config *ClusterExtensionConfigApplyConfiguration `json:"config,omitempty"`
	// progressDeadlineMinutes is an optional field that defines the maximum period
	// of time in minutes after which an installation should be considered failed and
	// require manual intervention. This functionality is disabled when no value
	// is provided. The minimum period is 10 minutes, and the maximum is 720 minutes (12 hours).
	//
	// <opcon:experimental>
	ProgressDeadlineMinutes *int32 `json:"progressDeadlineMinutes,omitempty"`
}

// ClusterExtensionSpecApplyConfiguration constructs a declarative configuration of the ClusterExtensionSpec type for use with
// apply.
func ClusterExtensionSpec() *ClusterExtensionSpecApplyConfiguration {
	return &ClusterExtensionSpecApplyConfiguration{}
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *ClusterExtensionSpecApplyConfiguration) WithNamespace(value string) *ClusterExtensionSpecApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithServiceAccount sets the ServiceAccount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceAccount field is set to the value of the last call.
func (b *ClusterExtensionSpecApplyConfiguration) WithServiceAccount(value *ServiceAccountReferenceApplyConfiguration) *ClusterExtensionSpecApplyConfiguration {
	b.ServiceAccount = value
	return b
}

// WithSource sets the Source field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Source field is set to the value of the last call.
func (b *ClusterExtensionSpecApplyConfiguration) WithSource(value *SourceConfigApplyConfiguration) *ClusterExtensionSpecApplyConfiguration {
	b.Source = value
	return b
}

// WithInstall sets the Install field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Install field is set to the value of the last call.
func (b *ClusterExtensionSpecApplyConfiguration) WithInstall(value *ClusterExtensionInstallConfigApplyConfiguration) *ClusterExtensionSpecApplyConfiguration {
	b.Install = value
	return b
}

// WithConfig sets the Config field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Config field is set to the value of the last call.
func (b *ClusterExtensionSpecApplyConfiguration) WithConfig(value *ClusterExtensionConfigApplyConfiguration) *ClusterExtensionSpecApplyConfiguration {
	b.Config = value
	return b
}

// WithProgressDeadlineMinutes sets the ProgressDeadlineMinutes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProgressDeadlineMinutes field is set to the value of the last call.
func (b *ClusterExtensionSpecApplyConfiguration) WithProgressDeadlineMinutes(value int32) *ClusterExtensionSpecApplyConfiguration {
	b.ProgressDeadlineMinutes = &value
	return b
}
