/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.21. DO NOT EDIT.

package v1

// OCIImageSourceApplyConfiguration represents a declarative configuration of the OCIImageSource type for use
// with apply.
//
// OCIImageSource identifies a bundle image to install directly from an OCI registry.
type OCIImageSourceApplyConfiguration struct {
	// ref is a Docker-style image reference with a tag or digest.
	Ref *string `json:"ref,omitempty"`
}

// OCIImageSourceApplyConfiguration constructs a declarative configuration of the OCIImageSource type for use with
// apply.
func OCIImageSource() *OCIImageSourceApplyConfiguration {
	return &OCIImageSourceApplyConfiguration{}
}

// WithRef sets the Ref field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ref field is set to the value of the last call.
func (b *OCIImageSourceApplyConfiguration) WithRef(value string) *OCIImageSourceApplyConfiguration {
	b.Ref = &value
	return b
}
