/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.21. DO NOT EDIT.

package v1

// ResolvedImageSourceApplyConfiguration represents a declarative configuration of the ResolvedImageSource type for use
// with apply.
//
// ResolvedImageSource provides information about the resolved source of a Catalog sourced from an image.
type ResolvedImageSourceApplyConfiguration struct {
	// ref contains the resolved image digest-based reference.
	// The digest format allows you to use other tooling to fetch the exact OCI manifests
	// that were used to extract the catalog contents.
	Ref *string `json:"ref,omitempty"`
	// catalogVersion is the monotonic version assigned to the catalog publication by the image publisher.
	// It is read from the OCI image config label "olm.operatorframework.io/catalog-version".
	// Older images without this label have no version. After a version is recorded, a different digest must have a
	// greater version before its content can replace the currently served catalog.
	CatalogVersion *int64 `json:"catalogVersion,omitempty"`
}

// ResolvedImageSourceApplyConfiguration constructs a declarative configuration of the ResolvedImageSource type for use with
// apply.
func ResolvedImageSource() *ResolvedImageSourceApplyConfiguration {
	return &ResolvedImageSourceApplyConfiguration{}
}

// WithRef sets the Ref field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ref field is set to the value of the last call.
func (b *ResolvedImageSourceApplyConfiguration) WithRef(value string) *ResolvedImageSourceApplyConfiguration {
	b.Ref = &value
	return b
}

// WithCatalogVersion sets the CatalogVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CatalogVersion field is set to the value of the last call.
func (b *ResolvedImageSourceApplyConfiguration) WithCatalogVersion(value int64) *ResolvedImageSourceApplyConfiguration {
	b.CatalogVersion = &value
	return b
}
