// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/operator-framework/operator-controller/internal/operator-controller/contentmanager (interfaces: Manager)
//
// Generated by this command:
//
//	mockgen -destination=contentmanager/mock_contentmanager.go -package=contentmanager github.com/operator-framework/operator-controller/internal/operator-controller/contentmanager Manager
//

// Package contentmanager is a generated GoMock package.
package contentmanager

import (
	context "context"
	reflect "reflect"

	v1 "github.com/operator-framework/operator-controller/api/v1"
	cache "github.com/operator-framework/operator-controller/internal/operator-controller/contentmanager/cache"
	gomock "go.uber.org/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
	isgomock struct{}
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockManager) Delete(arg0 *v1.ClusterExtension) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockManagerMockRecorder) Delete(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockManager)(nil).Delete), arg0)
}

// Get mocks base method.
func (m *MockManager) Get(arg0 context.Context, arg1 *v1.ClusterExtension) (cache.Cache, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(cache.Cache)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockManagerMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockManager)(nil).Get), arg0, arg1)
}
