module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.20

require github.com/bwplotka/bingo v0.8.0

require (
	github.com/Masterminds/semver v1.5.0 // indirect
	github.com/efficientgo/core v1.0.0-rc.0 // indirect
	github.com/oklog/run v1.1.0 // indirect
	golang.org/x/mod v0.5.1 // indirect
	golang.org/x/sync v0.0.0-20210220032951-036812b2e83c // indirect
	golang.org/x/sys v0.0.0-20220330033206-e17cdc41300f // indirect
	golang.org/x/term v0.0.0-20210927222741-03fcf44c2211 // indirect
	golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1 // indirect
	mvdan.cc/sh/v3 v3.4.3 // indirect
)
