module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.25.0

replace github.com/containerd/containerd => github.com/containerd/containerd v1.4.11

replace github.com/docker/distribution => github.com/docker/distribution v0.0.0-20191216044856-a8371794149d

replace github.com/mattn/go-sqlite3 => github.com/mattn/go-sqlite3 v1.10.0

replace github.com/go-git/go-git/v5 => github.com/go-git/go-git/v5 v5.19.2

require github.com/operator-framework/operator-sdk v1.41.1 // cmd/operator-sdk -tags=containers_image_openpgp -ldflags=-X=github.com/operator-framework/operator-sdk/internal/version.Version=v1.41.1
