module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.25.0

replace github.com/docker/distribution => github.com/docker/distribution v0.0.0-20191216044856-a8371794149d

replace github.com/go-git/go-git/v5 => github.com/go-git/go-git/v5 v5.19.2

require github.com/operator-framework/operator-registry v1.60.0 // cmd/opm -tags=containers_image_openpgp
