module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.23.0

toolchain go1.23.2

require sigs.k8s.io/controller-runtime/tools/setup-envtest v0.0.0-20250114080233-1ec7c1b76e98
