// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/operator-framework/operator-controller/internal/operator-controller/contentmanager/cache (interfaces: sourcerer,Watcher,CloserSyncingSource)
//
// Generated by this command:
//
//	mockgen -destination mock_sourcerer_gen_test.go -package cache -mock_names sourcerer=MockSourcerer github.com/operator-framework/operator-controller/internal/operator-controller/contentmanager/cache sourcerer,Watcher,CloserSyncingSource
//

// Package cache is a generated GoMock package.
package cache

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	workqueue "k8s.io/client-go/util/workqueue"
	client "sigs.k8s.io/controller-runtime/pkg/client"
	reconcile "sigs.k8s.io/controller-runtime/pkg/reconcile"
	source "sigs.k8s.io/controller-runtime/pkg/source"
)

// MockSourcerer is a mock of sourcerer interface.
type MockSourcerer struct {
	ctrl     *gomock.Controller
	recorder *MockSourcererMockRecorder
	isgomock struct{}
}

// MockSourcererMockRecorder is the mock recorder for MockSourcerer.
type MockSourcererMockRecorder struct {
	mock *MockSourcerer
}

// NewMockSourcerer creates a new mock instance.
func NewMockSourcerer(ctrl *gomock.Controller) *MockSourcerer {
	mock := &MockSourcerer{ctrl: ctrl}
	mock.recorder = &MockSourcererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSourcerer) EXPECT() *MockSourcererMockRecorder {
	return m.recorder
}

// Source mocks base method.
func (m *MockSourcerer) Source(arg0 schema.GroupVersionKind, arg1 client.Object, arg2 func(context.Context)) (CloserSyncingSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Source", arg0, arg1, arg2)
	ret0, _ := ret[0].(CloserSyncingSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Source indicates an expected call of Source.
func (mr *MockSourcererMockRecorder) Source(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Source", reflect.TypeOf((*MockSourcerer)(nil).Source), arg0, arg1, arg2)
}

// MockWatcher is a mock of Watcher interface.
type MockWatcher struct {
	ctrl     *gomock.Controller
	recorder *MockWatcherMockRecorder
	isgomock struct{}
}

// MockWatcherMockRecorder is the mock recorder for MockWatcher.
type MockWatcherMockRecorder struct {
	mock *MockWatcher
}

// NewMockWatcher creates a new mock instance.
func NewMockWatcher(ctrl *gomock.Controller) *MockWatcher {
	mock := &MockWatcher{ctrl: ctrl}
	mock.recorder = &MockWatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWatcher) EXPECT() *MockWatcherMockRecorder {
	return m.recorder
}

// Watch mocks base method.
func (m *MockWatcher) Watch(arg0 source.Source) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Watch", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Watch indicates an expected call of Watch.
func (mr *MockWatcherMockRecorder) Watch(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockWatcher)(nil).Watch), arg0)
}

// MockCloserSyncingSource is a mock of CloserSyncingSource interface.
type MockCloserSyncingSource struct {
	ctrl     *gomock.Controller
	recorder *MockCloserSyncingSourceMockRecorder
	isgomock struct{}
}

// MockCloserSyncingSourceMockRecorder is the mock recorder for MockCloserSyncingSource.
type MockCloserSyncingSourceMockRecorder struct {
	mock *MockCloserSyncingSource
}

// NewMockCloserSyncingSource creates a new mock instance.
func NewMockCloserSyncingSource(ctrl *gomock.Controller) *MockCloserSyncingSource {
	mock := &MockCloserSyncingSource{ctrl: ctrl}
	mock.recorder = &MockCloserSyncingSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCloserSyncingSource) EXPECT() *MockCloserSyncingSourceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockCloserSyncingSource) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockCloserSyncingSourceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockCloserSyncingSource)(nil).Close))
}

// Start mocks base method.
func (m *MockCloserSyncingSource) Start(arg0 context.Context, arg1 workqueue.TypedRateLimitingInterface[reconcile.Request]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockCloserSyncingSourceMockRecorder) Start(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockCloserSyncingSource)(nil).Start), arg0, arg1)
}

// WaitForSync mocks base method.
func (m *MockCloserSyncingSource) WaitForSync(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForSync", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitForSync indicates an expected call of WaitForSync.
func (mr *MockCloserSyncingSourceMockRecorder) WaitForSync(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForSync", reflect.TypeOf((*MockCloserSyncingSource)(nil).WaitForSync), ctx)
}
