// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/operator-framework/operator-controller/internal/object-controller/controllers (interfaces: RevisionEngine,RevisionEngineFactory)
//
// Generated by this command:
//
//	mockgen -destination=controllers/mocks_object_controller.go -package=controllers github.com/operator-framework/operator-controller/internal/object-controller/controllers RevisionEngine,RevisionEngineFactory
//

// Package controllers is a generated GoMock package.
package controllers

import (
	context "context"
	reflect "reflect"

	v1 "github.com/operator-framework/operator-controller/api/v1"
	controllers "github.com/operator-framework/operator-controller/internal/object-controller/controllers"
	gomock "go.uber.org/mock/gomock"
	machinery "pkg.package-operator.run/boxcutter/machinery"
	types "pkg.package-operator.run/boxcutter/machinery/types"
)

// MockRevisionEngine is a mock of RevisionEngine interface.
type MockRevisionEngine struct {
	ctrl     *gomock.Controller
	recorder *MockRevisionEngineMockRecorder
	isgomock struct{}
}

// MockRevisionEngineMockRecorder is the mock recorder for MockRevisionEngine.
type MockRevisionEngineMockRecorder struct {
	mock *MockRevisionEngine
}

// NewMockRevisionEngine creates a new mock instance.
func NewMockRevisionEngine(ctrl *gomock.Controller) *MockRevisionEngine {
	mock := &MockRevisionEngine{ctrl: ctrl}
	mock.recorder = &MockRevisionEngineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRevisionEngine) EXPECT() *MockRevisionEngineMockRecorder {
	return m.recorder
}

// Reconcile mocks base method.
func (m *MockRevisionEngine) Reconcile(ctx context.Context, rev types.Revision, opts ...types.RevisionReconcileOption) (machinery.RevisionResult, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, rev}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Reconcile", varargs...)
	ret0, _ := ret[0].(machinery.RevisionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reconcile indicates an expected call of Reconcile.
func (mr *MockRevisionEngineMockRecorder) Reconcile(ctx, rev any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, rev}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reconcile", reflect.TypeOf((*MockRevisionEngine)(nil).Reconcile), varargs...)
}

// Teardown mocks base method.
func (m *MockRevisionEngine) Teardown(ctx context.Context, rev types.Revision, opts ...types.RevisionTeardownOption) (machinery.RevisionTeardownResult, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, rev}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Teardown", varargs...)
	ret0, _ := ret[0].(machinery.RevisionTeardownResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Teardown indicates an expected call of Teardown.
func (mr *MockRevisionEngineMockRecorder) Teardown(ctx, rev any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, rev}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Teardown", reflect.TypeOf((*MockRevisionEngine)(nil).Teardown), varargs...)
}

// MockRevisionEngineFactory is a mock of RevisionEngineFactory interface.
type MockRevisionEngineFactory struct {
	ctrl     *gomock.Controller
	recorder *MockRevisionEngineFactoryMockRecorder
	isgomock struct{}
}

// MockRevisionEngineFactoryMockRecorder is the mock recorder for MockRevisionEngineFactory.
type MockRevisionEngineFactoryMockRecorder struct {
	mock *MockRevisionEngineFactory
}

// NewMockRevisionEngineFactory creates a new mock instance.
func NewMockRevisionEngineFactory(ctrl *gomock.Controller) *MockRevisionEngineFactory {
	mock := &MockRevisionEngineFactory{ctrl: ctrl}
	mock.recorder = &MockRevisionEngineFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRevisionEngineFactory) EXPECT() *MockRevisionEngineFactoryMockRecorder {
	return m.recorder
}

// CreateRevisionEngine mocks base method.
func (m *MockRevisionEngineFactory) CreateRevisionEngine(ctx context.Context, rev *v1.ClusterObjectSet) (controllers.RevisionEngine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRevisionEngine", ctx, rev)
	ret0, _ := ret[0].(controllers.RevisionEngine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRevisionEngine indicates an expected call of CreateRevisionEngine.
func (mr *MockRevisionEngineFactoryMockRecorder) CreateRevisionEngine(ctx, rev any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRevisionEngine", reflect.TypeOf((*MockRevisionEngineFactory)(nil).CreateRevisionEngine), ctx, rev)
}
