// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/operator-framework/operator-controller/internal/operator-controller/controllers (interfaces: CatalogCache,CatalogCachePopulator,RevisionStatesGetter,Applier)
//
// Generated by this command:
//
//	mockgen -destination=controllers/mocks_operator_controller.go -package=controllers github.com/operator-framework/operator-controller/internal/operator-controller/controllers CatalogCache,CatalogCachePopulator,RevisionStatesGetter,Applier
//

// Package controllers is a generated GoMock package.
package controllers

import (
	context "context"
	fs "io/fs"
	reflect "reflect"

	v1 "github.com/operator-framework/operator-controller/api/v1"
	controllers "github.com/operator-framework/operator-controller/internal/operator-controller/controllers"
	gomock "go.uber.org/mock/gomock"
)

// MockCatalogCache is a mock of CatalogCache interface.
type MockCatalogCache struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogCacheMockRecorder
	isgomock struct{}
}

// MockCatalogCacheMockRecorder is the mock recorder for MockCatalogCache.
type MockCatalogCacheMockRecorder struct {
	mock *MockCatalogCache
}

// NewMockCatalogCache creates a new mock instance.
func NewMockCatalogCache(ctrl *gomock.Controller) *MockCatalogCache {
	mock := &MockCatalogCache{ctrl: ctrl}
	mock.recorder = &MockCatalogCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalogCache) EXPECT() *MockCatalogCacheMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockCatalogCache) Get(catalogName, resolvedRef string) (fs.FS, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", catalogName, resolvedRef)
	ret0, _ := ret[0].(fs.FS)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCatalogCacheMockRecorder) Get(catalogName, resolvedRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCatalogCache)(nil).Get), catalogName, resolvedRef)
}

// Remove mocks base method.
func (m *MockCatalogCache) Remove(catalogName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", catalogName)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockCatalogCacheMockRecorder) Remove(catalogName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockCatalogCache)(nil).Remove), catalogName)
}

// MockCatalogCachePopulator is a mock of CatalogCachePopulator interface.
type MockCatalogCachePopulator struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogCachePopulatorMockRecorder
	isgomock struct{}
}

// MockCatalogCachePopulatorMockRecorder is the mock recorder for MockCatalogCachePopulator.
type MockCatalogCachePopulatorMockRecorder struct {
	mock *MockCatalogCachePopulator
}

// NewMockCatalogCachePopulator creates a new mock instance.
func NewMockCatalogCachePopulator(ctrl *gomock.Controller) *MockCatalogCachePopulator {
	mock := &MockCatalogCachePopulator{ctrl: ctrl}
	mock.recorder = &MockCatalogCachePopulatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalogCachePopulator) EXPECT() *MockCatalogCachePopulatorMockRecorder {
	return m.recorder
}

// PopulateCache mocks base method.
func (m *MockCatalogCachePopulator) PopulateCache(ctx context.Context, catalog *v1.ClusterCatalog) (fs.FS, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PopulateCache", ctx, catalog)
	ret0, _ := ret[0].(fs.FS)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PopulateCache indicates an expected call of PopulateCache.
func (mr *MockCatalogCachePopulatorMockRecorder) PopulateCache(ctx, catalog any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PopulateCache", reflect.TypeOf((*MockCatalogCachePopulator)(nil).PopulateCache), ctx, catalog)
}

// MockRevisionStatesGetter is a mock of RevisionStatesGetter interface.
type MockRevisionStatesGetter struct {
	ctrl     *gomock.Controller
	recorder *MockRevisionStatesGetterMockRecorder
	isgomock struct{}
}

// MockRevisionStatesGetterMockRecorder is the mock recorder for MockRevisionStatesGetter.
type MockRevisionStatesGetterMockRecorder struct {
	mock *MockRevisionStatesGetter
}

// NewMockRevisionStatesGetter creates a new mock instance.
func NewMockRevisionStatesGetter(ctrl *gomock.Controller) *MockRevisionStatesGetter {
	mock := &MockRevisionStatesGetter{ctrl: ctrl}
	mock.recorder = &MockRevisionStatesGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRevisionStatesGetter) EXPECT() *MockRevisionStatesGetterMockRecorder {
	return m.recorder
}

// GetRevisionStates mocks base method.
func (m *MockRevisionStatesGetter) GetRevisionStates(ctx context.Context, ext *v1.ClusterExtension) (*controllers.RevisionStates, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRevisionStates", ctx, ext)
	ret0, _ := ret[0].(*controllers.RevisionStates)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRevisionStates indicates an expected call of GetRevisionStates.
func (mr *MockRevisionStatesGetterMockRecorder) GetRevisionStates(ctx, ext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRevisionStates", reflect.TypeOf((*MockRevisionStatesGetter)(nil).GetRevisionStates), ctx, ext)
}

// MockApplier is a mock of Applier interface.
type MockApplier struct {
	ctrl     *gomock.Controller
	recorder *MockApplierMockRecorder
	isgomock struct{}
}

// MockApplierMockRecorder is the mock recorder for MockApplier.
type MockApplierMockRecorder struct {
	mock *MockApplier
}

// NewMockApplier creates a new mock instance.
func NewMockApplier(ctrl *gomock.Controller) *MockApplier {
	mock := &MockApplier{ctrl: ctrl}
	mock.recorder = &MockApplierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApplier) EXPECT() *MockApplierMockRecorder {
	return m.recorder
}

// Apply mocks base method.
func (m *MockApplier) Apply(arg0 context.Context, arg1 fs.FS, arg2 *v1.ClusterExtension, arg3, arg4 map[string]string) (bool, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Apply", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Apply indicates an expected call of Apply.
func (mr *MockApplierMockRecorder) Apply(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockApplier)(nil).Apply), arg0, arg1, arg2, arg3, arg4)
}
