// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/operator-framework/operator-controller/internal/operator-controller/applier (interfaces: Preflight,HelmReleaseToObjectsConverterInterface,HelmChartProvider,ClusterObjectSetGenerator,ManifestProvider)
//
// Generated by this command:
//
//	mockgen -destination=applier/mock_applier.go -package=applier github.com/operator-framework/operator-controller/internal/operator-controller/applier Preflight,HelmReleaseToObjectsConverterInterface,HelmChartProvider,ClusterObjectSetGenerator,ManifestProvider
//

// Package applier is a generated GoMock package.
package applier

import (
	context "context"
	fs "io/fs"
	reflect "reflect"

	v1 "github.com/operator-framework/operator-controller/api/v1"
	v10 "github.com/operator-framework/operator-controller/applyconfigurations/api/v1"
	gomock "go.uber.org/mock/gomock"
	chart "helm.sh/helm/v3/pkg/chart"
	release "helm.sh/helm/v3/pkg/release"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockPreflight is a mock of Preflight interface.
type MockPreflight struct {
	ctrl     *gomock.Controller
	recorder *MockPreflightMockRecorder
	isgomock struct{}
}

// MockPreflightMockRecorder is the mock recorder for MockPreflight.
type MockPreflightMockRecorder struct {
	mock *MockPreflight
}

// NewMockPreflight creates a new mock instance.
func NewMockPreflight(ctrl *gomock.Controller) *MockPreflight {
	mock := &MockPreflight{ctrl: ctrl}
	mock.recorder = &MockPreflightMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPreflight) EXPECT() *MockPreflightMockRecorder {
	return m.recorder
}

// Install mocks base method.
func (m *MockPreflight) Install(arg0 context.Context, arg1 []client.Object) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Install", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Install indicates an expected call of Install.
func (mr *MockPreflightMockRecorder) Install(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Install", reflect.TypeOf((*MockPreflight)(nil).Install), arg0, arg1)
}

// Upgrade mocks base method.
func (m *MockPreflight) Upgrade(arg0 context.Context, arg1 []client.Object) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upgrade", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upgrade indicates an expected call of Upgrade.
func (mr *MockPreflightMockRecorder) Upgrade(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upgrade", reflect.TypeOf((*MockPreflight)(nil).Upgrade), arg0, arg1)
}

// MockHelmReleaseToObjectsConverterInterface is a mock of HelmReleaseToObjectsConverterInterface interface.
type MockHelmReleaseToObjectsConverterInterface struct {
	ctrl     *gomock.Controller
	recorder *MockHelmReleaseToObjectsConverterInterfaceMockRecorder
	isgomock struct{}
}

// MockHelmReleaseToObjectsConverterInterfaceMockRecorder is the mock recorder for MockHelmReleaseToObjectsConverterInterface.
type MockHelmReleaseToObjectsConverterInterfaceMockRecorder struct {
	mock *MockHelmReleaseToObjectsConverterInterface
}

// NewMockHelmReleaseToObjectsConverterInterface creates a new mock instance.
func NewMockHelmReleaseToObjectsConverterInterface(ctrl *gomock.Controller) *MockHelmReleaseToObjectsConverterInterface {
	mock := &MockHelmReleaseToObjectsConverterInterface{ctrl: ctrl}
	mock.recorder = &MockHelmReleaseToObjectsConverterInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHelmReleaseToObjectsConverterInterface) EXPECT() *MockHelmReleaseToObjectsConverterInterfaceMockRecorder {
	return m.recorder
}

// GetObjectsFromRelease mocks base method.
func (m *MockHelmReleaseToObjectsConverterInterface) GetObjectsFromRelease(rel *release.Release) ([]client.Object, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectsFromRelease", rel)
	ret0, _ := ret[0].([]client.Object)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectsFromRelease indicates an expected call of GetObjectsFromRelease.
func (mr *MockHelmReleaseToObjectsConverterInterfaceMockRecorder) GetObjectsFromRelease(rel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectsFromRelease", reflect.TypeOf((*MockHelmReleaseToObjectsConverterInterface)(nil).GetObjectsFromRelease), rel)
}

// MockHelmChartProvider is a mock of HelmChartProvider interface.
type MockHelmChartProvider struct {
	ctrl     *gomock.Controller
	recorder *MockHelmChartProviderMockRecorder
	isgomock struct{}
}

// MockHelmChartProviderMockRecorder is the mock recorder for MockHelmChartProvider.
type MockHelmChartProviderMockRecorder struct {
	mock *MockHelmChartProvider
}

// NewMockHelmChartProvider creates a new mock instance.
func NewMockHelmChartProvider(ctrl *gomock.Controller) *MockHelmChartProvider {
	mock := &MockHelmChartProvider{ctrl: ctrl}
	mock.recorder = &MockHelmChartProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHelmChartProvider) EXPECT() *MockHelmChartProviderMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockHelmChartProvider) Get(bundle fs.FS, clusterExtension *v1.ClusterExtension) (*chart.Chart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", bundle, clusterExtension)
	ret0, _ := ret[0].(*chart.Chart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockHelmChartProviderMockRecorder) Get(bundle, clusterExtension any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockHelmChartProvider)(nil).Get), bundle, clusterExtension)
}

// MockClusterObjectSetGenerator is a mock of ClusterObjectSetGenerator interface.
type MockClusterObjectSetGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockClusterObjectSetGeneratorMockRecorder
	isgomock struct{}
}

// MockClusterObjectSetGeneratorMockRecorder is the mock recorder for MockClusterObjectSetGenerator.
type MockClusterObjectSetGeneratorMockRecorder struct {
	mock *MockClusterObjectSetGenerator
}

// NewMockClusterObjectSetGenerator creates a new mock instance.
func NewMockClusterObjectSetGenerator(ctrl *gomock.Controller) *MockClusterObjectSetGenerator {
	mock := &MockClusterObjectSetGenerator{ctrl: ctrl}
	mock.recorder = &MockClusterObjectSetGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClusterObjectSetGenerator) EXPECT() *MockClusterObjectSetGeneratorMockRecorder {
	return m.recorder
}

// GenerateRevision mocks base method.
func (m *MockClusterObjectSetGenerator) GenerateRevision(ctx context.Context, bundleFS fs.FS, ext *v1.ClusterExtension, objectLabels, revisionAnnotations map[string]string) (*v10.ClusterObjectSetApplyConfiguration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateRevision", ctx, bundleFS, ext, objectLabels, revisionAnnotations)
	ret0, _ := ret[0].(*v10.ClusterObjectSetApplyConfiguration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateRevision indicates an expected call of GenerateRevision.
func (mr *MockClusterObjectSetGeneratorMockRecorder) GenerateRevision(ctx, bundleFS, ext, objectLabels, revisionAnnotations any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateRevision", reflect.TypeOf((*MockClusterObjectSetGenerator)(nil).GenerateRevision), ctx, bundleFS, ext, objectLabels, revisionAnnotations)
}

// GenerateRevisionFromHelmRelease mocks base method.
func (m *MockClusterObjectSetGenerator) GenerateRevisionFromHelmRelease(ctx context.Context, helmRelease *release.Release, ext *v1.ClusterExtension, objectLabels map[string]string) (*v10.ClusterObjectSetApplyConfiguration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateRevisionFromHelmRelease", ctx, helmRelease, ext, objectLabels)
	ret0, _ := ret[0].(*v10.ClusterObjectSetApplyConfiguration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateRevisionFromHelmRelease indicates an expected call of GenerateRevisionFromHelmRelease.
func (mr *MockClusterObjectSetGeneratorMockRecorder) GenerateRevisionFromHelmRelease(ctx, helmRelease, ext, objectLabels any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateRevisionFromHelmRelease", reflect.TypeOf((*MockClusterObjectSetGenerator)(nil).GenerateRevisionFromHelmRelease), ctx, helmRelease, ext, objectLabels)
}

// MockManifestProvider is a mock of ManifestProvider interface.
type MockManifestProvider struct {
	ctrl     *gomock.Controller
	recorder *MockManifestProviderMockRecorder
	isgomock struct{}
}

// MockManifestProviderMockRecorder is the mock recorder for MockManifestProvider.
type MockManifestProviderMockRecorder struct {
	mock *MockManifestProvider
}

// NewMockManifestProvider creates a new mock instance.
func NewMockManifestProvider(ctrl *gomock.Controller) *MockManifestProvider {
	mock := &MockManifestProvider{ctrl: ctrl}
	mock.recorder = &MockManifestProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManifestProvider) EXPECT() *MockManifestProviderMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockManifestProvider) Get(bundle fs.FS, ext *v1.ClusterExtension) ([]client.Object, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", bundle, ext)
	ret0, _ := ret[0].([]client.Object)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockManifestProviderMockRecorder) Get(bundle, ext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockManifestProvider)(nil).Get), bundle, ext)
}
