// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/operator-framework/operator-controller/internal/catalogd/service (interfaces: GraphQLService)
//
// Generated by this command:
//
//	mockgen -destination=catalogdservice/mock_graphqlservice.go -package=catalogdservice github.com/operator-framework/operator-controller/internal/catalogd/service GraphQLService
//

// Package catalogdservice is a generated GoMock package.
package catalogdservice

import (
	fs "io/fs"
	reflect "reflect"

	graphql "github.com/graphql-go/graphql"
	graphql0 "github.com/operator-framework/operator-controller/internal/catalogd/graphql"
	gomock "go.uber.org/mock/gomock"
)

// MockGraphQLService is a mock of GraphQLService interface.
type MockGraphQLService struct {
	ctrl     *gomock.Controller
	recorder *MockGraphQLServiceMockRecorder
	isgomock struct{}
}

// MockGraphQLServiceMockRecorder is the mock recorder for MockGraphQLService.
type MockGraphQLServiceMockRecorder struct {
	mock *MockGraphQLService
}

// NewMockGraphQLService creates a new mock instance.
func NewMockGraphQLService(ctrl *gomock.Controller) *MockGraphQLService {
	mock := &MockGraphQLService{ctrl: ctrl}
	mock.recorder = &MockGraphQLServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGraphQLService) EXPECT() *MockGraphQLServiceMockRecorder {
	return m.recorder
}

// ExecuteQuery mocks base method.
func (m *MockGraphQLService) ExecuteQuery(catalog string, catalogFS fs.FS, query string) (*graphql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteQuery", catalog, catalogFS, query)
	ret0, _ := ret[0].(*graphql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteQuery indicates an expected call of ExecuteQuery.
func (mr *MockGraphQLServiceMockRecorder) ExecuteQuery(catalog, catalogFS, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteQuery", reflect.TypeOf((*MockGraphQLService)(nil).ExecuteQuery), catalog, catalogFS, query)
}

// GetSchema mocks base method.
func (m *MockGraphQLService) GetSchema(catalog string, catalogFS fs.FS) (*graphql0.DynamicSchema, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSchema", catalog, catalogFS)
	ret0, _ := ret[0].(*graphql0.DynamicSchema)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSchema indicates an expected call of GetSchema.
func (mr *MockGraphQLServiceMockRecorder) GetSchema(catalog, catalogFS any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSchema", reflect.TypeOf((*MockGraphQLService)(nil).GetSchema), catalog, catalogFS)
}

// InvalidateCache mocks base method.
func (m *MockGraphQLService) InvalidateCache(catalog string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InvalidateCache", catalog)
}

// InvalidateCache indicates an expected call of InvalidateCache.
func (mr *MockGraphQLServiceMockRecorder) InvalidateCache(catalog any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateCache", reflect.TypeOf((*MockGraphQLService)(nil).InvalidateCache), catalog)
}
