{{- if .Values.options.operatorController.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: clusterextension-serviceaccount-deprecated
  labels:
    app.kubernetes.io/name: operator-controller
    {{- include "olmv1.labels" . | nindent 4 }}
  annotations:
    {{- include "olmv1.annotations" . | nindent 4 }}
spec:
  policyName: clusterextension-serviceaccount-deprecated
  validationActions:
    - Warn
{{- end }}
