---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: olm.operatorframework.io/v1
kind: ClusterExtension
metadata:
  name: argocd
spec:
  namespace: argocd
  source:
    sourceType: Catalog
    catalog:
      packageName: argocd-operator
      version: 0.6.0
