// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/operator-framework/helm-operator-plugins/pkg/client (interfaces: ActionInterface,ActionClientGetter)
//
// Generated by this command:
//
//	mockgen -destination=helmclient/mock_actionclient.go -package=helmclient github.com/operator-framework/helm-operator-plugins/pkg/client ActionInterface,ActionClientGetter
//

// Package helmclient is a generated GoMock package.
package helmclient

import (
	context "context"
	reflect "reflect"

	client "github.com/operator-framework/helm-operator-plugins/pkg/client"
	gomock "go.uber.org/mock/gomock"
	action "helm.sh/helm/v3/pkg/action"
	chart "helm.sh/helm/v3/pkg/chart"
	release "helm.sh/helm/v3/pkg/release"
	client0 "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockActionInterface is a mock of ActionInterface interface.
type MockActionInterface struct {
	ctrl     *gomock.Controller
	recorder *MockActionInterfaceMockRecorder
	isgomock struct{}
}

// MockActionInterfaceMockRecorder is the mock recorder for MockActionInterface.
type MockActionInterfaceMockRecorder struct {
	mock *MockActionInterface
}

// NewMockActionInterface creates a new mock instance.
func NewMockActionInterface(ctrl *gomock.Controller) *MockActionInterface {
	mock := &MockActionInterface{ctrl: ctrl}
	mock.recorder = &MockActionInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActionInterface) EXPECT() *MockActionInterfaceMockRecorder {
	return m.recorder
}

// Config mocks base method.
func (m *MockActionInterface) Config() *action.Configuration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Config")
	ret0, _ := ret[0].(*action.Configuration)
	return ret0
}

// Config indicates an expected call of Config.
func (mr *MockActionInterfaceMockRecorder) Config() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockActionInterface)(nil).Config))
}

// Get mocks base method.
func (m *MockActionInterface) Get(name string, opts ...client.GetOption) (*release.Release, error) {
	m.ctrl.T.Helper()
	varargs := []any{name}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*release.Release)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockActionInterfaceMockRecorder) Get(name any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{name}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockActionInterface)(nil).Get), varargs...)
}

// History mocks base method.
func (m *MockActionInterface) History(name string, opts ...client.HistoryOption) ([]*release.Release, error) {
	m.ctrl.T.Helper()
	varargs := []any{name}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "History", varargs...)
	ret0, _ := ret[0].([]*release.Release)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// History indicates an expected call of History.
func (mr *MockActionInterfaceMockRecorder) History(name any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{name}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "History", reflect.TypeOf((*MockActionInterface)(nil).History), varargs...)
}

// Install mocks base method.
func (m *MockActionInterface) Install(name, namespace string, chrt *chart.Chart, vals map[string]any, opts ...client.InstallOption) (*release.Release, error) {
	m.ctrl.T.Helper()
	varargs := []any{name, namespace, chrt, vals}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Install", varargs...)
	ret0, _ := ret[0].(*release.Release)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Install indicates an expected call of Install.
func (mr *MockActionInterfaceMockRecorder) Install(name, namespace, chrt, vals any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{name, namespace, chrt, vals}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Install", reflect.TypeOf((*MockActionInterface)(nil).Install), varargs...)
}

// Reconcile mocks base method.
func (m *MockActionInterface) Reconcile(rel *release.Release) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reconcile", rel)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reconcile indicates an expected call of Reconcile.
func (mr *MockActionInterfaceMockRecorder) Reconcile(rel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reconcile", reflect.TypeOf((*MockActionInterface)(nil).Reconcile), rel)
}

// Uninstall mocks base method.
func (m *MockActionInterface) Uninstall(name string, opts ...client.UninstallOption) (*release.UninstallReleaseResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{name}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Uninstall", varargs...)
	ret0, _ := ret[0].(*release.UninstallReleaseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Uninstall indicates an expected call of Uninstall.
func (mr *MockActionInterfaceMockRecorder) Uninstall(name any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{name}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Uninstall", reflect.TypeOf((*MockActionInterface)(nil).Uninstall), varargs...)
}

// Upgrade mocks base method.
func (m *MockActionInterface) Upgrade(name, namespace string, chrt *chart.Chart, vals map[string]any, opts ...client.UpgradeOption) (*release.Release, error) {
	m.ctrl.T.Helper()
	varargs := []any{name, namespace, chrt, vals}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Upgrade", varargs...)
	ret0, _ := ret[0].(*release.Release)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upgrade indicates an expected call of Upgrade.
func (mr *MockActionInterfaceMockRecorder) Upgrade(name, namespace, chrt, vals any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{name, namespace, chrt, vals}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upgrade", reflect.TypeOf((*MockActionInterface)(nil).Upgrade), varargs...)
}

// MockActionClientGetter is a mock of ActionClientGetter interface.
type MockActionClientGetter struct {
	ctrl     *gomock.Controller
	recorder *MockActionClientGetterMockRecorder
	isgomock struct{}
}

// MockActionClientGetterMockRecorder is the mock recorder for MockActionClientGetter.
type MockActionClientGetterMockRecorder struct {
	mock *MockActionClientGetter
}

// NewMockActionClientGetter creates a new mock instance.
func NewMockActionClientGetter(ctrl *gomock.Controller) *MockActionClientGetter {
	mock := &MockActionClientGetter{ctrl: ctrl}
	mock.recorder = &MockActionClientGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActionClientGetter) EXPECT() *MockActionClientGetterMockRecorder {
	return m.recorder
}

// ActionClientFor mocks base method.
func (m *MockActionClientGetter) ActionClientFor(ctx context.Context, obj client0.Object) (client.ActionInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActionClientFor", ctx, obj)
	ret0, _ := ret[0].(client.ActionInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ActionClientFor indicates an expected call of ActionClientFor.
func (mr *MockActionClientGetterMockRecorder) ActionClientFor(ctx, obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActionClientFor", reflect.TypeOf((*MockActionClientGetter)(nil).ActionClientFor), ctx, obj)
}
