// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/operator-framework/operator-controller/internal/testutil/mock/helmclient (interfaces: ActionClientGetterAndInterface)
//
// Generated by this command:
//
//	mockgen -destination=helmclient/mock_composite.go -package=helmclient github.com/operator-framework/operator-controller/internal/testutil/mock/helmclient ActionClientGetterAndInterface
//

// Package helmclient is a generated GoMock package.
package helmclient

import (
	context "context"
	reflect "reflect"

	client "github.com/operator-framework/helm-operator-plugins/pkg/client"
	gomock "go.uber.org/mock/gomock"
	action "helm.sh/helm/v3/pkg/action"
	chart "helm.sh/helm/v3/pkg/chart"
	release "helm.sh/helm/v3/pkg/release"
	client0 "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockActionClientGetterAndInterface is a mock of ActionClientGetterAndInterface interface.
type MockActionClientGetterAndInterface struct {
	ctrl     *gomock.Controller
	recorder *MockActionClientGetterAndInterfaceMockRecorder
	isgomock struct{}
}

// MockActionClientGetterAndInterfaceMockRecorder is the mock recorder for MockActionClientGetterAndInterface.
type MockActionClientGetterAndInterfaceMockRecorder struct {
	mock *MockActionClientGetterAndInterface
}

// NewMockActionClientGetterAndInterface creates a new mock instance.
func NewMockActionClientGetterAndInterface(ctrl *gomock.Controller) *MockActionClientGetterAndInterface {
	mock := &MockActionClientGetterAndInterface{ctrl: ctrl}
	mock.recorder = &MockActionClientGetterAndInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActionClientGetterAndInterface) EXPECT() *MockActionClientGetterAndInterfaceMockRecorder {
	return m.recorder
}

// ActionClientFor mocks base method.
func (m *MockActionClientGetterAndInterface) ActionClientFor(ctx context.Context, obj client0.Object) (client.ActionInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActionClientFor", ctx, obj)
	ret0, _ := ret[0].(client.ActionInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ActionClientFor indicates an expected call of ActionClientFor.
func (mr *MockActionClientGetterAndInterfaceMockRecorder) ActionClientFor(ctx, obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActionClientFor", reflect.TypeOf((*MockActionClientGetterAndInterface)(nil).ActionClientFor), ctx, obj)
}

// Config mocks base method.
func (m *MockActionClientGetterAndInterface) Config() *action.Configuration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Config")
	ret0, _ := ret[0].(*action.Configuration)
	return ret0
}

// Config indicates an expected call of Config.
func (mr *MockActionClientGetterAndInterfaceMockRecorder) Config() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockActionClientGetterAndInterface)(nil).Config))
}

// Get mocks base method.
func (m *MockActionClientGetterAndInterface) Get(name string, opts ...client.GetOption) (*release.Release, error) {
	m.ctrl.T.Helper()
	varargs := []any{name}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*release.Release)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockActionClientGetterAndInterfaceMockRecorder) Get(name any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{name}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockActionClientGetterAndInterface)(nil).Get), varargs...)
}

// History mocks base method.
func (m *MockActionClientGetterAndInterface) History(name string, opts ...client.HistoryOption) ([]*release.Release, error) {
	m.ctrl.T.Helper()
	varargs := []any{name}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "History", varargs...)
	ret0, _ := ret[0].([]*release.Release)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// History indicates an expected call of History.
func (mr *MockActionClientGetterAndInterfaceMockRecorder) History(name any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{name}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "History", reflect.TypeOf((*MockActionClientGetterAndInterface)(nil).History), varargs...)
}

// Install mocks base method.
func (m *MockActionClientGetterAndInterface) Install(name, namespace string, chrt *chart.Chart, vals map[string]any, opts ...client.InstallOption) (*release.Release, error) {
	m.ctrl.T.Helper()
	varargs := []any{name, namespace, chrt, vals}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Install", varargs...)
	ret0, _ := ret[0].(*release.Release)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Install indicates an expected call of Install.
func (mr *MockActionClientGetterAndInterfaceMockRecorder) Install(name, namespace, chrt, vals any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{name, namespace, chrt, vals}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Install", reflect.TypeOf((*MockActionClientGetterAndInterface)(nil).Install), varargs...)
}

// Reconcile mocks base method.
func (m *MockActionClientGetterAndInterface) Reconcile(rel *release.Release) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reconcile", rel)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reconcile indicates an expected call of Reconcile.
func (mr *MockActionClientGetterAndInterfaceMockRecorder) Reconcile(rel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reconcile", reflect.TypeOf((*MockActionClientGetterAndInterface)(nil).Reconcile), rel)
}

// Uninstall mocks base method.
func (m *MockActionClientGetterAndInterface) Uninstall(name string, opts ...client.UninstallOption) (*release.UninstallReleaseResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{name}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Uninstall", varargs...)
	ret0, _ := ret[0].(*release.UninstallReleaseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Uninstall indicates an expected call of Uninstall.
func (mr *MockActionClientGetterAndInterfaceMockRecorder) Uninstall(name any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{name}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Uninstall", reflect.TypeOf((*MockActionClientGetterAndInterface)(nil).Uninstall), varargs...)
}

// Upgrade mocks base method.
func (m *MockActionClientGetterAndInterface) Upgrade(name, namespace string, chrt *chart.Chart, vals map[string]any, opts ...client.UpgradeOption) (*release.Release, error) {
	m.ctrl.T.Helper()
	varargs := []any{name, namespace, chrt, vals}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Upgrade", varargs...)
	ret0, _ := ret[0].(*release.Release)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upgrade indicates an expected call of Upgrade.
func (mr *MockActionClientGetterAndInterfaceMockRecorder) Upgrade(name, namespace, chrt, vals any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{name, namespace, chrt, vals}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upgrade", reflect.TypeOf((*MockActionClientGetterAndInterface)(nil).Upgrade), varargs...)
}
