#!/bin/bash
set -euo pipefail
# Outputs the kindest/node image for the given K8S_VERSION.
# The KIND_IMAGES block below is regenerated by `make kind-update-images`.

if [ -z "${K8S_VERSION:-}" ]; then
    echo "Error: K8S_VERSION is not set." >&2
    exit 1
fi

K8S_MINOR=$(echo "${K8S_VERSION}" | sed -E 's/^v?([0-9]+\.[0-9]+).*/\1/')

# --- BEGIN KIND IMAGES ---
# kind v0.32.0
case "${K8S_MINOR}" in
  1.33) IMAGE="kindest/node:v1.33.12" ;;
  1.34) IMAGE="kindest/node:v1.34.8" ;;
  1.35) IMAGE="kindest/node:v1.35.5" ;;
  1.36) IMAGE="kindest/node:v1.36.1" ;;
  *) IMAGE="" ;;
esac
# --- END KIND IMAGES ---

if [ -z "${IMAGE}" ]; then
    echo "Error: no kindest/node image for k8s ${K8S_MINOR}." >&2
    echo "Run 'make kind-update-images' after bumping kind." >&2
    exit 1
fi
echo "${IMAGE}"
