// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/operator-framework/operator-controller/internal/operator-controller/authorization (interfaces: PreAuthorizer)
//
// Generated by this command:
//
//	mockgen -destination=authorization/mock_authorization.go -package=authorization github.com/operator-framework/operator-controller/internal/operator-controller/authorization PreAuthorizer
//

// Package authorization is a generated GoMock package.
package authorization

import (
	context "context"
	io "io"
	reflect "reflect"

	authorization "github.com/operator-framework/operator-controller/internal/operator-controller/authorization"
	gomock "go.uber.org/mock/gomock"
	user "k8s.io/apiserver/pkg/authentication/user"
)

// MockPreAuthorizer is a mock of PreAuthorizer interface.
type MockPreAuthorizer struct {
	ctrl     *gomock.Controller
	recorder *MockPreAuthorizerMockRecorder
	isgomock struct{}
}

// MockPreAuthorizerMockRecorder is the mock recorder for MockPreAuthorizer.
type MockPreAuthorizerMockRecorder struct {
	mock *MockPreAuthorizer
}

// NewMockPreAuthorizer creates a new mock instance.
func NewMockPreAuthorizer(ctrl *gomock.Controller) *MockPreAuthorizer {
	mock := &MockPreAuthorizer{ctrl: ctrl}
	mock.recorder = &MockPreAuthorizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPreAuthorizer) EXPECT() *MockPreAuthorizerMockRecorder {
	return m.recorder
}

// PreAuthorize mocks base method.
func (m *MockPreAuthorizer) PreAuthorize(ctx context.Context, arg1 user.Info, manifestReader io.Reader, additionalRequiredPerms ...authorization.UserAuthorizerAttributesFactory) ([]authorization.ScopedPolicyRules, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, arg1, manifestReader}
	for _, a := range additionalRequiredPerms {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PreAuthorize", varargs...)
	ret0, _ := ret[0].([]authorization.ScopedPolicyRules)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PreAuthorize indicates an expected call of PreAuthorize.
func (mr *MockPreAuthorizerMockRecorder) PreAuthorize(ctx, arg1, manifestReader any, additionalRequiredPerms ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, arg1, manifestReader}, additionalRequiredPerms...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreAuthorize", reflect.TypeOf((*MockPreAuthorizer)(nil).PreAuthorize), varargs...)
}
