// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/operator-framework/operator-controller/internal/catalogd/storage (interfaces: Instance)
//
// Generated by this command:
//
//	mockgen -destination=storage/mock_instance.go -package=storage github.com/operator-framework/operator-controller/internal/catalogd/storage Instance
//

// Package storage is a generated GoMock package.
package storage

import (
	context "context"
	fs "io/fs"
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInstance is a mock of Instance interface.
type MockInstance struct {
	ctrl     *gomock.Controller
	recorder *MockInstanceMockRecorder
	isgomock struct{}
}

// MockInstanceMockRecorder is the mock recorder for MockInstance.
type MockInstanceMockRecorder struct {
	mock *MockInstance
}

// NewMockInstance creates a new mock instance.
func NewMockInstance(ctrl *gomock.Controller) *MockInstance {
	mock := &MockInstance{ctrl: ctrl}
	mock.recorder = &MockInstanceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInstance) EXPECT() *MockInstanceMockRecorder {
	return m.recorder
}

// BaseURL mocks base method.
func (m *MockInstance) BaseURL(catalog string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BaseURL", catalog)
	ret0, _ := ret[0].(string)
	return ret0
}

// BaseURL indicates an expected call of BaseURL.
func (mr *MockInstanceMockRecorder) BaseURL(catalog any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BaseURL", reflect.TypeOf((*MockInstance)(nil).BaseURL), catalog)
}

// ContentExists mocks base method.
func (m *MockInstance) ContentExists(catalog string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContentExists", catalog)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ContentExists indicates an expected call of ContentExists.
func (mr *MockInstanceMockRecorder) ContentExists(catalog any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContentExists", reflect.TypeOf((*MockInstance)(nil).ContentExists), catalog)
}

// Delete mocks base method.
func (m *MockInstance) Delete(catalog string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", catalog)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockInstanceMockRecorder) Delete(catalog any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockInstance)(nil).Delete), catalog)
}

// StorageServerHandler mocks base method.
func (m *MockInstance) StorageServerHandler() http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StorageServerHandler")
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// StorageServerHandler indicates an expected call of StorageServerHandler.
func (mr *MockInstanceMockRecorder) StorageServerHandler() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StorageServerHandler", reflect.TypeOf((*MockInstance)(nil).StorageServerHandler))
}

// Store mocks base method.
func (m *MockInstance) Store(ctx context.Context, catalog string, fsys fs.FS) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, catalog, fsys)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockInstanceMockRecorder) Store(ctx, catalog, fsys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockInstance)(nil).Store), ctx, catalog, fsys)
}
