// Code generated by MockGen. DO NOT EDIT.
// Source: clusterobjectset_controller.go
//
// Generated by this command:
//
//	mockgen -source clusterobjectset_controller.go -destination mock_trackingcache_gen_test.go -package controllers -mock_names trackingCache=MockTrackingCache -exclude_interfaces Sourcoser
//

// Package controllers is a generated GoMock package.
package controllers

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	sets "k8s.io/apimachinery/pkg/util/sets"
	client "sigs.k8s.io/controller-runtime/pkg/client"
	handler "sigs.k8s.io/controller-runtime/pkg/handler"
	predicate "sigs.k8s.io/controller-runtime/pkg/predicate"
	source "sigs.k8s.io/controller-runtime/pkg/source"
)

// MockTrackingCache is a mock of trackingCache interface.
type MockTrackingCache struct {
	ctrl     *gomock.Controller
	recorder *MockTrackingCacheMockRecorder
	isgomock struct{}
}

// MockTrackingCacheMockRecorder is the mock recorder for MockTrackingCache.
type MockTrackingCacheMockRecorder struct {
	mock *MockTrackingCache
}

// NewMockTrackingCache creates a new mock instance.
func NewMockTrackingCache(ctrl *gomock.Controller) *MockTrackingCache {
	mock := &MockTrackingCache{ctrl: ctrl}
	mock.recorder = &MockTrackingCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrackingCache) EXPECT() *MockTrackingCacheMockRecorder {
	return m.recorder
}

// Free mocks base method.
func (m *MockTrackingCache) Free(ctx context.Context, user client.Object) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Free", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Free indicates an expected call of Free.
func (mr *MockTrackingCacheMockRecorder) Free(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Free", reflect.TypeOf((*MockTrackingCache)(nil).Free), ctx, user)
}

// Get mocks base method.
func (m *MockTrackingCache) Get(ctx context.Context, key client.ObjectKey, obj client.Object, opts ...client.GetOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key, obj}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockTrackingCacheMockRecorder) Get(ctx, key, obj any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key, obj}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTrackingCache)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockTrackingCache) List(ctx context.Context, list client.ObjectList, opts ...client.ListOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, list}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockTrackingCacheMockRecorder) List(ctx, list any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, list}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTrackingCache)(nil).List), varargs...)
}

// Source mocks base method.
func (m *MockTrackingCache) Source(arg0 handler.EventHandler, predicates ...predicate.Predicate) source.Source {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range predicates {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Source", varargs...)
	ret0, _ := ret[0].(source.Source)
	return ret0
}

// Source indicates an expected call of Source.
func (mr *MockTrackingCacheMockRecorder) Source(arg0 any, predicates ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, predicates...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Source", reflect.TypeOf((*MockTrackingCache)(nil).Source), varargs...)
}

// Watch mocks base method.
func (m *MockTrackingCache) Watch(ctx context.Context, user client.Object, gvks sets.Set[schema.GroupVersionKind]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Watch", ctx, user, gvks)
	ret0, _ := ret[0].(error)
	return ret0
}

// Watch indicates an expected call of Watch.
func (mr *MockTrackingCacheMockRecorder) Watch(ctx, user, gvks any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockTrackingCache)(nil).Watch), ctx, user, gvks)
}
