// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/operator-framework/operator-controller/internal/operator-controller/rukpak/render (interfaces: CertificateProvider)
//
// Generated by this command:
//
//	mockgen -destination=render/mock_certprovider.go -package=render github.com/operator-framework/operator-controller/internal/operator-controller/rukpak/render CertificateProvider
//

// Package render is a generated GoMock package.
package render

import (
	reflect "reflect"

	render "github.com/operator-framework/operator-controller/internal/operator-controller/rukpak/render"
	gomock "go.uber.org/mock/gomock"
	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockCertificateProvider is a mock of CertificateProvider interface.
type MockCertificateProvider struct {
	ctrl     *gomock.Controller
	recorder *MockCertificateProviderMockRecorder
	isgomock struct{}
}

// MockCertificateProviderMockRecorder is the mock recorder for MockCertificateProvider.
type MockCertificateProviderMockRecorder struct {
	mock *MockCertificateProvider
}

// NewMockCertificateProvider creates a new mock instance.
func NewMockCertificateProvider(ctrl *gomock.Controller) *MockCertificateProvider {
	mock := &MockCertificateProvider{ctrl: ctrl}
	mock.recorder = &MockCertificateProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCertificateProvider) EXPECT() *MockCertificateProviderMockRecorder {
	return m.recorder
}

// AdditionalObjects mocks base method.
func (m *MockCertificateProvider) AdditionalObjects(cfg render.CertificateProvisionerConfig) ([]unstructured.Unstructured, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdditionalObjects", cfg)
	ret0, _ := ret[0].([]unstructured.Unstructured)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdditionalObjects indicates an expected call of AdditionalObjects.
func (mr *MockCertificateProviderMockRecorder) AdditionalObjects(cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdditionalObjects", reflect.TypeOf((*MockCertificateProvider)(nil).AdditionalObjects), cfg)
}

// GetCertSecretInfo mocks base method.
func (m *MockCertificateProvider) GetCertSecretInfo(cfg render.CertificateProvisionerConfig) render.CertSecretInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCertSecretInfo", cfg)
	ret0, _ := ret[0].(render.CertSecretInfo)
	return ret0
}

// GetCertSecretInfo indicates an expected call of GetCertSecretInfo.
func (mr *MockCertificateProviderMockRecorder) GetCertSecretInfo(cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCertSecretInfo", reflect.TypeOf((*MockCertificateProvider)(nil).GetCertSecretInfo), cfg)
}

// InjectCABundle mocks base method.
func (m *MockCertificateProvider) InjectCABundle(obj client.Object, cfg render.CertificateProvisionerConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InjectCABundle", obj, cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InjectCABundle indicates an expected call of InjectCABundle.
func (mr *MockCertificateProviderMockRecorder) InjectCABundle(obj, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InjectCABundle", reflect.TypeOf((*MockCertificateProvider)(nil).InjectCABundle), obj, cfg)
}
