// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/operator-framework/operator-controller/internal/operator-controller/config (interfaces: SchemaProvider)
//
// Generated by this command:
//
//	mockgen -destination=config/mock_schemaprovider.go -package=config github.com/operator-framework/operator-controller/internal/operator-controller/config SchemaProvider
//

// Package config is a generated GoMock package.
package config

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSchemaProvider is a mock of SchemaProvider interface.
type MockSchemaProvider struct {
	ctrl     *gomock.Controller
	recorder *MockSchemaProviderMockRecorder
	isgomock struct{}
}

// MockSchemaProviderMockRecorder is the mock recorder for MockSchemaProvider.
type MockSchemaProviderMockRecorder struct {
	mock *MockSchemaProvider
}

// NewMockSchemaProvider creates a new mock instance.
func NewMockSchemaProvider(ctrl *gomock.Controller) *MockSchemaProvider {
	mock := &MockSchemaProvider{ctrl: ctrl}
	mock.recorder = &MockSchemaProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSchemaProvider) EXPECT() *MockSchemaProviderMockRecorder {
	return m.recorder
}

// GetConfigSchema mocks base method.
func (m *MockSchemaProvider) GetConfigSchema() (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigSchema")
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigSchema indicates an expected call of GetConfigSchema.
func (mr *MockSchemaProviderMockRecorder) GetConfigSchema() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigSchema", reflect.TypeOf((*MockSchemaProvider)(nil).GetConfigSchema))
}
