// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/operator-framework/operator-controller/internal/catalogd/server (interfaces: CatalogStore)
//
// Generated by this command:
//
//	mockgen -destination=catalogdserver/mock_catalogstore.go -package=catalogdserver github.com/operator-framework/operator-controller/internal/catalogd/server CatalogStore
//

// Package catalogdserver is a generated GoMock package.
package catalogdserver

import (
	fs "io/fs"
	os "os"
	reflect "reflect"

	server "github.com/operator-framework/operator-controller/internal/catalogd/server"
	gomock "go.uber.org/mock/gomock"
)

// MockCatalogStore is a mock of CatalogStore interface.
type MockCatalogStore struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogStoreMockRecorder
	isgomock struct{}
}

// MockCatalogStoreMockRecorder is the mock recorder for MockCatalogStore.
type MockCatalogStoreMockRecorder struct {
	mock *MockCatalogStore
}

// NewMockCatalogStore creates a new mock instance.
func NewMockCatalogStore(ctrl *gomock.Controller) *MockCatalogStore {
	mock := &MockCatalogStore{ctrl: ctrl}
	mock.recorder = &MockCatalogStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalogStore) EXPECT() *MockCatalogStoreMockRecorder {
	return m.recorder
}

// GetCatalogData mocks base method.
func (m *MockCatalogStore) GetCatalogData(catalog string) (*os.File, os.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCatalogData", catalog)
	ret0, _ := ret[0].(*os.File)
	ret1, _ := ret[1].(os.FileInfo)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetCatalogData indicates an expected call of GetCatalogData.
func (mr *MockCatalogStoreMockRecorder) GetCatalogData(catalog any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCatalogData", reflect.TypeOf((*MockCatalogStore)(nil).GetCatalogData), catalog)
}

// GetCatalogFS mocks base method.
func (m *MockCatalogStore) GetCatalogFS(catalog string) (fs.FS, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCatalogFS", catalog)
	ret0, _ := ret[0].(fs.FS)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCatalogFS indicates an expected call of GetCatalogFS.
func (mr *MockCatalogStoreMockRecorder) GetCatalogFS(catalog any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCatalogFS", reflect.TypeOf((*MockCatalogStore)(nil).GetCatalogFS), catalog)
}

// GetIndex mocks base method.
func (m *MockCatalogStore) GetIndex(catalog string) (server.Index, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIndex", catalog)
	ret0, _ := ret[0].(server.Index)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIndex indicates an expected call of GetIndex.
func (mr *MockCatalogStoreMockRecorder) GetIndex(catalog any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIndex", reflect.TypeOf((*MockCatalogStore)(nil).GetIndex), catalog)
}
