name: update-demos

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'api/*'
      - 'config/*'
      - 'test/e2e/features/demos.feature'
      - 'test/e2e/steps/demo_steps.go'
      - 'test/e2e/steps/asciicast_*.go'
      - '.github/workflows/update-demos.yaml'
  pull_request:
    paths:
      - 'api/*'
      - 'config/*'
      - 'test/e2e/features/demos.feature'
      - 'test/e2e/steps/demo_steps.go'
      - 'test/e2e/steps/asciicast_*.go'
      - '.github/workflows/update-demos.yaml'

jobs:
  generate-demos:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      TERM: linux
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: actions/setup-go@v6.5.0
        with:
          go-version-file: "go.mod"
      - uses: actions/setup-python@v6.2.0
        with:
          python-version: 3.x
          cache: pip
      - name: Generate demo recordings
        run: make update-demos

      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: demo-recordings
          path: |
            docs/demos/*.cast
            docs/demos/*.svg

      - name: Deploy docs with updated demos
        if: github.event_name == 'push'
        run: make deploy-docs
