// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/operator-framework/operator-controller/internal/operator-controller/contentmanager/cache (interfaces: Cache,Watcher,CloserSyncingSource)
//
// Generated by this command:
//
//	mockgen -destination=cmcache/mock_cache.go -package=cmcache github.com/operator-framework/operator-controller/internal/operator-controller/contentmanager/cache Cache,Watcher,CloserSyncingSource
//

// Package cmcache is a generated GoMock package.
package cmcache

import (
	context "context"
	reflect "reflect"

	cache "github.com/operator-framework/operator-controller/internal/operator-controller/contentmanager/cache"
	gomock "go.uber.org/mock/gomock"
	workqueue "k8s.io/client-go/util/workqueue"
	client "sigs.k8s.io/controller-runtime/pkg/client"
	reconcile "sigs.k8s.io/controller-runtime/pkg/reconcile"
	source "sigs.k8s.io/controller-runtime/pkg/source"
)

// MockCache is a mock of Cache interface.
type MockCache struct {
	ctrl     *gomock.Controller
	recorder *MockCacheMockRecorder
	isgomock struct{}
}

// MockCacheMockRecorder is the mock recorder for MockCache.
type MockCacheMockRecorder struct {
	mock *MockCache
}

// NewMockCache creates a new mock instance.
func NewMockCache(ctrl *gomock.Controller) *MockCache {
	mock := &MockCache{ctrl: ctrl}
	mock.recorder = &MockCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCache) EXPECT() *MockCacheMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockCache) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockCacheMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockCache)(nil).Close))
}

// Watch mocks base method.
func (m *MockCache) Watch(arg0 context.Context, arg1 cache.Watcher, arg2 ...client.Object) error {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Watch", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Watch indicates an expected call of Watch.
func (mr *MockCacheMockRecorder) Watch(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockCache)(nil).Watch), varargs...)
}

// MockWatcher is a mock of Watcher interface.
type MockWatcher struct {
	ctrl     *gomock.Controller
	recorder *MockWatcherMockRecorder
	isgomock struct{}
}

// MockWatcherMockRecorder is the mock recorder for MockWatcher.
type MockWatcherMockRecorder struct {
	mock *MockWatcher
}

// NewMockWatcher creates a new mock instance.
func NewMockWatcher(ctrl *gomock.Controller) *MockWatcher {
	mock := &MockWatcher{ctrl: ctrl}
	mock.recorder = &MockWatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWatcher) EXPECT() *MockWatcherMockRecorder {
	return m.recorder
}

// Watch mocks base method.
func (m *MockWatcher) Watch(arg0 source.Source) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Watch", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Watch indicates an expected call of Watch.
func (mr *MockWatcherMockRecorder) Watch(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockWatcher)(nil).Watch), arg0)
}

// MockCloserSyncingSource is a mock of CloserSyncingSource interface.
type MockCloserSyncingSource struct {
	ctrl     *gomock.Controller
	recorder *MockCloserSyncingSourceMockRecorder
	isgomock struct{}
}

// MockCloserSyncingSourceMockRecorder is the mock recorder for MockCloserSyncingSource.
type MockCloserSyncingSourceMockRecorder struct {
	mock *MockCloserSyncingSource
}

// NewMockCloserSyncingSource creates a new mock instance.
func NewMockCloserSyncingSource(ctrl *gomock.Controller) *MockCloserSyncingSource {
	mock := &MockCloserSyncingSource{ctrl: ctrl}
	mock.recorder = &MockCloserSyncingSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCloserSyncingSource) EXPECT() *MockCloserSyncingSourceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockCloserSyncingSource) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockCloserSyncingSourceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockCloserSyncingSource)(nil).Close))
}

// Start mocks base method.
func (m *MockCloserSyncingSource) Start(arg0 context.Context, arg1 workqueue.TypedRateLimitingInterface[reconcile.Request]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockCloserSyncingSourceMockRecorder) Start(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockCloserSyncingSource)(nil).Start), arg0, arg1)
}

// WaitForSync mocks base method.
func (m *MockCloserSyncingSource) WaitForSync(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForSync", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitForSync indicates an expected call of WaitForSync.
func (mr *MockCloserSyncingSourceMockRecorder) WaitForSync(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForSync", reflect.TypeOf((*MockCloserSyncingSource)(nil).WaitForSync), ctx)
}
